version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"login-app","imageUri":"%s"}]' 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
env:
  variables:
    ECR_REPOSITORY: 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app
    IMAGE_REPO_NAME: 010526269382.dkr.ecr.us-east-1.amazonaws.com/login-app
    IMAGE_TAG: latest
